services:
  discovery-service:
    build: ./discovery-service
    container_name: discovery-dock
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:8761/actuator/health" ]
      interval:  10s
      retries:  4
  config-service:
    build: ./config-service
    container_name: config-dock
    ports:
      - '9999:9999'
    expose:
      - '9999'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
    depends_on:
      discovery-service:
        condition:  service_healthy
  client-service:
    build: ./client-service
    container_name: client-dock
    ports:
      - '9091:9091'
    expose:
      - '9091'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:9091/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      - CONFIG_SERVICE_URL=http://config-dock:9999
    depends_on:
      config-service:
        condition: service_healthy
  produit-service:
    build: ./produit-service
    container_name: produit-dock
    ports:
      - '9092:9092'
    expose:
      - '9092'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:9092/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      - CONFIG_SERVICE_URL=http://config-dock:9999
    depends_on:
      config-service:
        condition: service_healthy
  commande-service:
    build: ./commande-sevice
    container_name: commande-dock
    ports:
      - '9093:9093'
    expose:
      - '9093'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:9093/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      - CONFIG_SERVICE_URL=http://config-dock:9999
    depends_on:
      config-service:
        condition:  service_healthy
      client-service:
        condition: service_healthy
      produit-service:
        condition: service_healthy
  gateway-service:
    build: ./gateway-service
    container_name: gateway-dock
    ports:
      - '8888:8888'
    expose:
      - '8888'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:8888/actuator/health" ]
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      - CONFIG_SERVICE_URL=http://config-dock:9999
    depends_on:
      commande-service:
        condition: service_healthy



